"""Add new fields

Revision ID: 0bf9a9ffb6aa
Revises: 5856fd24b54c
Create Date: 2024-08-25 14:37:59.797638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf9a9ffb6aa'
down_revision = '5856fd24b54c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('file_path', sa.String(length=150), nullable=True))
    op.add_column('product', sa.Column('file_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'file_type')
    op.drop_column('product', 'file_path')
    # ### end Alembic commands ###
