"""Add editing and deleting capabilities to messages

Revision ID: 5856fd24b54c
Revises: 2171016ef160
Create Date: 2024-08-25 10:15:04.300304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5856fd24b54c'
down_revision = '2171016ef160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('edited', sa.Boolean(), nullable=True))
    op.add_column('message', sa.Column('edit_timestamp', sa.DateTime(), nullable=True))
    op.add_column('message', sa.Column('deleted_for_sender', sa.Boolean(), nullable=True))
    op.add_column('message', sa.Column('deleted_for_receiver', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'deleted_for_receiver')
    op.drop_column('message', 'deleted_for_sender')
    op.drop_column('message', 'edit_timestamp')
    op.drop_column('message', 'edited')
    # ### end Alembic commands ###
