"""Add image and is_sold fields to Product model

Revision ID: e18b4a565ae3
Revises: 01003a52fdcb
Create Date: 2024-08-02 08:22:00.169491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18b4a565ae3'
down_revision = '01003a52fdcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('is_sold', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_sold')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
